### PR TITLE
 Performance improvement

### PR DESCRIPTION
**Pull request by jcabak**
- Text remains visible during webfont load

### CODE REVIEW

**Comment by AlCutter** [comment]
Hi Jakub, thanks for another improvement here!

Could you rebase just the last commit ("Performance improvement") onto master?

**Comment by jcabak** [comment]
> Hi Jakub, thanks for another improvement here!
> 
> Could you rebase just the last commit ("Performance improvement") onto master?

Done.

**Comment by AlCutter** [comment]
Ah, that's a merge, but I'm trying to just get this PR to be _just_ the "Performance improvement" commit on top of upstream/master (if you're not sure how to do that I can try to help)

**Comment by jcabak** [comment]
Hmm, I made `git rebase`, I was thinking it is enough, should I type other command?

**Comment by AlCutter** [comment]
The easiest thing might be if I open another PR with just your commit in it - it should say the commit is authored by jcabak and committed by me so it'll still be attributed to you - does that sound ok?

(The commands I used to clip the commit out were something along the lines of `git reset --hard HEAD~1` to drop the latest merge commit, and then `git rebase --onto upstream/master HEAD~1` to snip off just the "performance improvement" commit and rebase it onto the upstream main branch.)

**Pull request closed without merging**
